export const regions = [
  "CA - San Diego South",
  "New Hampshire",
  "Massachusetts",
  "Maine",
  "Rhode Island",
].sort();

export const breaks = [
  {
    break_name: "Pacific Beach",
    location: "San Diego",
    region: "CA - San Diego South",
    lat: "32.8025",
    lng: "-117.2356",
  },
  {
    break_name: "The Wall",
    location: "Hampton Beach, New Hampshire",
    region: "New Hampshire",
    lat: "42.9340",
    lng: "-70.7984",
  },
  {
    break_name: "Long Sands Beach",
    location: "York, Maine",
    region: "Maine",
    lat: "43.158845",
    lng: "-70.610971",
  },
  {
    break_name: "Wells Beach",
    location: "Wells, Maine",
    region: "Maine",
    lat: "43.303143",
    lng: "-70.560127",
  },
  {
    break_name: "Ogunquit",
    location: "Ogunquit, Maine",
    region: "Maine",
    lat: "43.255950",
    lng: "-70.589231",
  },
  {
    break_name: "Gooch's Beach",
    location: "Kennebunk, Maine",
    region: "Maine",
    lat: "43.345847",
    lng: "-70.481133",
  },
  {
    break_name: "Higgins Beach",
    location: "Scarborough, Maine",
    region: "Maine",
    lat: "43.560229",
    lng: "-70.275599",
  },
  {
    break_name: "Old Orchard Beach",
    location: "Old Orchard Beach, Maine",
    region: "Maine",
    lat: "43.516102",
    lng: "-70.366669",
  },
  {
    break_name: "Scarborough Beach",
    location: "Scarborough, Maine",
    region: "Maine",
    lat: "43.545352",
    lng: "-70.305681",
  },
  {
    break_name: "Seabrook Beach",
    location: "Seabrook, New Hampshire",
    region: "New Hampshire",
    lat: "42.887337",
    lng: "-70.813027",
  },
  {
    break_name: "Fox Hill",
    location: "North Hampton, New Hampshire",
    region: "New Hampshire",
    lat: "42.963968",
    lng: "-70.769600",
  },
  {
    break_name: "Sawyer's Beach",
    location: "Rye, New Hampshire",
    region: "New Hampshire",
    lat: "42.978967",
    lng: "-70.764412",
  },
  {
    break_name: "Jenness Beach",
    location: "Rye, New Hampshire",
    region: "New Hampshire",
    lat: "42.985750",
    lng: "-70.761851",
  },
  {
    break_name: "Long Beach",
    location: "Gloucester, Massachusetts",
    region: "Massachusetts",
    lat: "42.629691",
    lng: "-70.616453",
  },
  {
    break_name: "Nahant Beach",
    location: "Nahant, Massachusetts",
    region: "Massachusetts",
    lat: "42.443614",
    lng: "-70.936530",
  },
  {
    break_name: "Nantasket Beach",
    location: "Hull, Massachusetts",
    region: "Massachusetts",
    lat: "42.275450",
    lng: "-70.859822",
  },
  // {
  //   break_name: "",
  //   location: ", Massachusetts",
  //   region: "MA - Cape Cod",
  //   lat: "",
  //   lng: "",
  // },
  // {
  //   break_name: "",
  //   location: ", Massachusetts",
  //   region: "MA - Cape Cod",
  //   lat: "",
  //   lng: "",
  // },
  // {
  //   break_name: "",
  //   location: ", Massachusetts",
  //   region: "MA - Cape Cod",
  //   lat: "",
  //   lng: "",
  // },
];
